### ISSUE TITLE
Memory issues when using large numbers of 'rois'

### ISSUE THREAD

**Issue by rob-mccutcheon** [rmarkello/abagen#154]
I would like to obtain gene expression values for an atlas where each voxel is labelled as a separate ROI (the roi*gene matrix will therefore be very sparse)

The issue is that this seems to require over 100GB of RAM

What I am doing is similar to  https://github.com/rmarkello/abagen/issues/46 (except the mask is the entire cortex)

Is there any recommendation  as to how to reduce the memory requirements?

Thank you!

Rob

**Comment by rmarkello** [comment]
Hi @robmcc10—thanks for your interest in, and welcome to, `abagen` !

Yikes! 100GB is certainly a lot of memory, so that's not ideal... This is likely due to the creation of the output `(n_voxels x genes)` matrices that get concatenated when aggregating across donors, which in the current workflow is unavoidable, though I'd have to check that this is indeed where the issue is arising.

To make sure I'm understanding, effectively you want the original ~3,700 samples assigned to voxels in your image, but preprocessed according to all the steps in the `get_expression_data()` pipeline? That seems like something that should be feasible, but the current workflow isn't really set up for this. (Also, the current pipeline is not optimized for speed in this instance, either! Apologies if it took _ages_ to run before raising a MemoryError 😬)

I don't think any quick combination of functions in `abagen` will resolve this for you, unfortunately, but you could pull out (most of) the internals of the `get_expression_data()` pipeline to do it. I recognize that's not something that's super appealing, so I'll take a look at maybe creating a "preprocessing" function that will just return the preprocessed microarry data. It would be relatively straightforward to match that up to voxels in your using the MNI coordinates provided by the AHBA annotation files!

I haven't had much time to work on this lately (as you can likely tell from the history), but I'll try and take a whack at this soon to see if I can get something working in short order. Let me know if my interpretation of your goal is accurate, though!

**Comment by robmcc10** [comment]
Yes the issue is the creation of the output, the error message is:

`MemoryError: Unable to allocate 26.7 GiB for an array with shape (15633, 229007) and data type float64`

_effectively you want the original ~3,700 samples assigned to voxels in your image, but preprocessed according to all the steps in the get_expression_data() pipeline?_ 

Yes that's right - so preprocessed according to the pipeline (including assignment to the improve MNI coordinates), but there is no 'aggregation within an ROI' step as each ROI will have max one sample. This work easily if you are using a smallish mask - but you get this issue when the mask gets too big.

Thanks again for putting together such a useful tool!

**Comment by rmarkello** [comment]
Hey @rob-mccutcheon ! I realize that this probably isn't _super_ helpful since I'm about a month late (apologies! grad school is busy...), but I just added a new change that should hopefully address your use case. If you update abagen by installing directly from github (`pip install --upgrade https://github.com/rmarkello/abagen`) you should have access to a new function: `abagen.get_samples_in_mask()`.

By default, running this function with no parameters will return expression data for all available samples (that haven't been discarded due to e.g., bad spatial normalization) as well as the MNI coordinates of those samples:

```python
>>> import abagen
>>> expression, coordinates = abagen.get_samples_in_mask()
>>> print(expression.shape, coordinates.shape)
(3466, 15633) (3466, 3)
```

This function accepts (almost) all the keyword arguments that `abagen.get_expression_data()` does, so you can simply provide those as parameters and they should work:

```python
>>> expression, coordinates = abagen.get_samples_in_mask(gene_norm='zscore', corrected_mni=False)
```

(Exceptions are noted in the doc-string of the function.) 

Alternatively, if you only want, say, cortical samples, you can provide a cortical mask and it will return only those samples that fall within `tolerance` mm of the bounds of that mask:

```python
>>> expression, coordinates = abagen.get_samples_in_mask(mask=my_cortical_mask, tolerance=2)
```

I've added some documentation on this function [here](https://abagen.readthedocs.io/en/latest/user_guide/mask.html), but feel free to let me know if anything is unclear about this!

---

I know that this isn't exactly what you'd hoped for, so I wanted to explain my reasoning a bit: there are a few tissue samples that are _very_ close to one another, so if you provided, say, a 1mm isotropic atlas to `abagen.get_expression_data()` (and avoided memory errors) you would end up having these samples aggregated into the same voxel. While you could use `return_counts=True` to check for which voxels this was the case, I figured providing all the samples + their corresponding coordinates would allow more flexibility: if you want to aggregate samples within 1mm voxels, go for it; if not, you have the "processed" sample-level data so you can do whatever you'd like.

Assuming you _do_ have a 1mm atlas, you can get the corresponding ijk values of the sample expression coordinates in your atlas space with:

```python
>>> import nibabel as nib
>>> import numpy as np
>>> affine = nib.load(my_atlas).affine
>>> ijk = np.asarray(np.floor(nib.affines.apply_affine(np.linalg.inv(affine), coordinates)), dtype='int')
```

If your atlas is a slightly different resolution you'll have to replace the `np.floor` call with something else (`np.around(coordinates * (1 / resolution)) / (1 / resolution)`, where resolution is e.g., `1` for 1mm isotropic, `2` for 2mm isotropic, etc.), but hopefully that's not the case 🤞

As said before, let me know if you have any questions about this, and thanks for raising the issue in the first place—I'll work on beefing up the documentation further to hopefully help people avoid these sorts of memory errors in the future.

**Comment by rob-mccutcheon** [comment]
Thank you so much for taking the time @rmarkello ! That looks like a great solution
