### ISSUE TITLE
Section 3.1 error

### ISSUE THREAD

**Issue by bjgunasekera** [rmarkello/abagen#166]
Hi, 
This is my first time using abagen. I am replicating the tutorial. All works well until section 3.1 

When I run: 
>>> expression = abagen.get_expression_data(atlas['image'], atlas['info'])

I get the error attached. Any advice would be much appreciated.

Best wishes,
Brandon

[abagen_error.txt](https://github.com/rmarkello/abagen/files/5814190/abagen_error.txt)

**Comment by rmarkello** [comment]
Hi @bjgunasekera, and welcome to `abagen`!!

This is a bit of a confusing error, so to help figure out what's causing it could I ask you to try a few things / provide some additional information?

First, what version of `abagen` are you using? You should be able to find this out by running `abagen --version` from the command line! I assume it's the latest (0.0.7) but if not, it would be great to know otherwise.

Second, what happens if you try and run `pd.read_csv(atlas['info'])` immediately prior to that line of code that caused the error? Does that work, or do you still get the same error? If you're getting an error, can you let me know what version of pandas you're using? The output of the command `import pandas; pandas.show_versions()` would be super helpful, here!

Sorry to not be of more immediate help, but hopefully this info will help us figure out what's causing the issue!

**Comment by bjgunasekera** [comment]
Hi @rmarkello,

Many thanks for your response, and the warm welcome. 

1) Yes, version 0.0.7 (exact output is 0.0.7+12.g0346891)
2) When I run pd.read_csv(atlas['info']), the same error persists. 

I've attached the output of the command import pandas; pandas.show_versions().

Best wishes,
Brandon
[pandas_version.txt](https://github.com/rmarkello/abagen/files/5815415/pandas_version.txt)

**Comment by rmarkello** [comment]
Got it, thanks so much! This appears to be an incompatibility issue with the newest version of `pandas`, released this past December. I'm working on a fix now and will ping you here when it's merged in :+1:

If you can't wait for that fix you can optionally downgrade `pandas` to the most recently tested + working version: 1.1.3. But I don't imagine this fix will take more than a few hours to implement, test, and merge, so hopefully you're able to wait! :grin:

Thanks again for catching this issue!

**Comment by rmarkello** [comment]
Alright @bjgunasekera, I just merged in what I hope will be a fix for your issue. If you can install `abagen` from the master branch (via e.g., `pip install git+https://github.com/rmarkello/abagen`) and give the tutorial another go that would be great ! Let me know if the problem persists or if it seems resolved and I'll close the issue accordingly.

Thanks again for bringing this to my attention!

**Comment by bjgunasekera** [comment]
Hi @rmarkello,

Apologies for the delay. Had some minor issues running from my C drive so moved everything to an ext hard drive. Your patch has solved the issue. Will let you know if anything else arises.

Bw,
Brandon
