### ISSUE TITLE
TypeError: argument of type 'method' is not iterable

### ISSUE THREAD

**Issue by daamartins** [rmarkello/abagen#168]
Dear all

I have used abagen successfully in the past. I am trying to rerun the same script i wrote in the past and that worked well, but now i get the error

**Comment by daamartins** [comment]
... 
TypeError: argument of type 'method' is not iterable

when i try to run 
expression = abagen.get_expression_data(atlas['image'], atlas['info'], exact=False)

Any idea about why this might be happening?

Thanks in advance

**Comment by rmarkello** [comment]
Hi @daamartins ! Thanks for reaching out with this issue (and welcome to `abagen` 👋).

It sounds like this might be the same compatibility issue between `abagen` and some newer versions of `pandas` that was recently identified in #166. I'd made a few tweaks to address this issue (#167) but hadn't gotten around to making a new release of `abagen` since then. I've gone ahead now, though, and cut a new release (version 0.0.8!) and pushed it to PyPi. If you update your `abagen` installation (e.g., with `pip install --upgrade abagen`) you shouldn't run into this issue anymore 🤞

Let me know if you have any questions or if the problem persists after you update your installation of `abagen`! If that fixes it we'll go ahead and close this issue.

**Comment by rmarkello** [comment]
(Sorry @daamartins I didn't realized you'd actually commented before—with a `pandas`-related issue, nonetheless! Welcome _back_, and thanks again for raising these issues!)

**Comment by rmarkello** [comment]
Hey @daamartins ! I hope that this new updated resolved your problems; I'm going to go and ahead and close this issue but feel free to comment again if you're still having problems and I'll re-open it, as needed.
