### ISSUE TITLE
add further atlases or keep it lightweight? [enhancement]

### ISSUE THREAD

**Issue by PeerHerholz** [rmarkello/abagen#18]
From the documentation I understand that the [Desikan-Killiany atlas](https://surfer.nmr.mgh.harvard.edu/ftp/articles/desikan06-parcellation.pdf) is included to provide an example of how to use the toolbox and that's it's comparable easy to use any atlas one might want. However, it might be a nice feature if some well-known and heavily used parcellations would already be included. Depending on your thoughts and how you want the toolbox structure and size to be, I would be happy to help out (e.g. including some atlases I already have in [ALPACA](https://github.com/C0C0AN/ALPACA/tree/master/resources/regions_of_interest)). To keep it lightweight, [nilearn's `fetch.datasets` functions](http://nilearn.github.io/modules/reference.html#module-nilearn.datasets) could be used to get the atlas files, while the respective csv could be included in the toolbox.

**Comment by rmarkello** [comment]
Hey @PeerHerholz! Thanks so much for reaching out with the suggestion. :slightly_smiling_face: 

This is something that I've been thinking about for various projects since it came up in miykael/atlasreader#4, and I unfortunately I have yet to settle on a good solution. I'd love to be able to use the atlas fetchers in `nilearn`, but unfortunately the metadata provided with the atlases aren't consistent enough to rely on. It would be great if something like [HAWG](https://github.com/INCF/HAWG-examples) could be adopted to standardize the metadata, but we're not there yet.

So my question in response to your question is: how would you decide which atlases to include? I have trouble settling on a relatively concise list, myself, and really only included the DK atlas because it's convenient (low resolution = quick to test!). I would be alright including a small list (maybe <5 atlases) I think, but worry that this is something that could quickly balloon out of proportion... Let me know your thoughts!

**Comment by miykael** [comment]
As @PeerHerholz sais, the question is **lightweight** or not. A `nilearn` `fetch_` approach is probably possible, the metadata are not too chaotic and I'm sure that a PR to `nilearn` could take care of any issues.

But as I mention here (https://github.com/miykael/atlasreader/pull/60#issuecomment-424442889), I see some other issues with using `nilearn`s `fetch_` approach. The main one is the problem of file size. `nilearn` is prone to download much more than you need. But also this could perhaps been taken care of with a PR to `nilearn`.

**Comment by emdupre** [comment]
@illdopejake is currently working to standardize nilearn fetchers, which might help here !

**Comment by rmarkello** [comment]
I'm going to close this since I think at the current juncture including atlases is outside the scope of `abagen`. Will maybe revisit at a later point but the plan is to stick to just processing and workflows, with the DK atlas included purely for example purposes.
