### ISSUE TITLE
Intensity-based probe filtering for each donor separately

### ISSUE THREAD

**Issue by daedhalus** [rmarkello/abagen#194]
Hi, I use abagen to perform the pre-processing steps for each of the six donors _individually_, one donor at a time (specifying `donors=['XX']` in the main function). How exactly does the intensity-based probe filtering work here, since it normally uses the 50% threshold across all tissue samples _across donors_ (which is not given in the described scenario)?
Thanks!

**Comment by rmarkello** [comment]
Hi @daedhalus ! :wave:

In this case the thresholding would _only_ consider samples for the specified donor, so you would be thresholding based on a different number of samples per donor. Instead of this, you may want to consider using `return_donors=True` with `donors='all'`. If you do this, the output of the `get_expression_data()` function will be a list of region-by-gene matrices, with one matrix per donor.

Let me know if that helps or if you have any other questions!

**Comment by daedhalus** [comment]
That helps tremendously, thank you very much!
