### ISSUE TITLE
Error using downloaded data

### ISSUE THREAD

**Issue by pmccolganni** [rmarkello/abagen#42]
Hi Ross, 

I am keen to use your code to generate genes for a parcellation scheme. 

I have already downloaded the allen data as have been using for a while however when I use

import abagen
files = abagen.fetch_microarray(data_dir='/Users/petermccolgan/github/abagen/allen_data', donors='all')

It starts downloading the data again and creates a allenbrain folder in that path. 

I already have the data downloaded in that path and just wanted to point to where it is. 

Do you know how i do this? 

On the off chance you're at OHBM this week it would be great to meet up and get a few pointers if you're free (no worries if not though)

Thanks

Peter

**Comment by pmccolganni** [comment]
Have downloaded data successfully but getting the following error;

/Users/petermccolgan/miniconda2/envs/nighres/lib/python3.6/site-packages/scipy/ndimage/measurements.py:1328: RuntimeWarning: invalid value encountered in true_divide
  for dir in range(input.ndim)]
(nighres) Peters-MacBook-Pro-3:abagen petermccolgan$ 

Thanks 

Peter

**Comment by rmarkello** [comment]
Hi Peter! Welcome to abagen and thanks for the issue! As you can see there are still some issues to work out with `abagen`, but I appreciate your motivation to use it.

Regarding the download (even though you've already resolved it): if you rename your directory 'allenbrain' and then use the path to the directory that 'allenbrain' is located in it should work, like:

```python
import abagen
files = abagen.fetch_microarray(data_dir='/Users/petermccolgan/github/abagen', donors='all')
```

Regarding the second issue: I'm not sure what command you ran to get that error, so if you're able to share the calling command I can maybe try and recreate the issue and, hopefully, help resolve it!

**Comment by rmarkello** [comment]
Just following up with a quick comment on this to make sure that there's a record of the conversation that @pmccolganni and I had in-person.

Essentially, besides the somewhat obscure instructions on how to use `abagen.fetch_microarray` with a pre-specified `data_dir` (addressed in my previousc omment), there didn't appear to be any issues. The `RuntimeWarning` being raised was simply that&mdash;a warning&mdash;and the code was running to completion. There is some concern that `abagen` is ignoring some of the ROIs in @pmccolganni's atlas file that is still TBD, but that is unrelated to the initial warning and errors.

Since the `RuntimeWarning` is being raised on the example atlas file I am going to open a new issue to determine where it's coming from and what we can do to squash it.
