### ISSUE TITLE
Output values

### ISSUE THREAD

**Issue by pmccolganni** [rmarkello/abagen#47]
Hi Ross, 

I just wanted to check something. The values I get are between 0 and 1. 

At the risk if asking a stupid question, can I assume that 1 is highest gene expression and 0 is lowest, when I am comparing expression levels across regions?

Thanks again for all your help. 

bw

Peter

**Comment by rmarkello** [comment]
Hi Peter! Yes, that is correct. The values are scaled using the following function:

https://github.com/rmarkello/abagen/blob/195293a9219ca1fbacf46ecbed4350f41d7faba9/abagen/process.py#L322-L357

You can see in the line 348:

```
scaled = (srs - srs_min) / (srs_max - srs_min)
```

that after the sigmoid normalization we're just doing a min-max scaling procedure so that all the values fall between 0 and 1. I am working on potentially adding other normalization procedures (e.g., z-score without scaling; see #45), but for now this is the only available between-donor normalization built in to the code base.

Let me know if you have any other questions!
